--
--
-- -- After loading the Java-specific configuration
-- local lspconfig = require("lspconfig")
--
-- -- Configure jdtls (Java LSP)
-- lspconfig.jdtls.setup({
--   -- Java LSP options
--   on_attach = function(client, bufnr)
--     -- You can set up keymaps or other actions when the LSP attaches to the Java file
--     local opts = { noremap = true, silent = true }
--     -- Example: Organize imports
--     vim.api.nvim_buf_set_keymap(bufnr, "n", "<leader>ji", "<cmd>lua require('jc.jdtls').organize_imports(true)<CR>", opts)
--   end,
-- })
